import type { DraftOutput, Persona } from "@mailapp/shared";
import { llmCalls } from "../../db/schema.js";
import type { DraftInput, LlmDeps, LlmProvider, LlmResult, ResearchInput } from "./provider.js";

/**
 * Deterministic provider for tests, CI and dry-runs. Produces plausible output from the lead
 * record alone; never calls the network. Behaviour can be tweaked per lead through the `notes`
 * column: "mock:fail-research", "mock:fail-draft", "mock:long-draft", "mock:banned".
 */
export class MockLlmProvider implements LlmProvider {
  readonly name = "mock" as const;
  constructor(private readonly deps: LlmDeps) {}

  private flag(input: { lead: { notes: string | null } }, f: string): boolean {
    return (input.lead.notes ?? "").includes(`mock:${f}`);
  }

  private async record(purpose: "research" | "draft", model: string, ids: { leadId?: string; campaignId?: string }, ok: boolean) {
    this.deps.metrics.emit("llm_calls", 1, { purpose });
    try {
      await this.deps.db.insert(llmCalls).values({
        leadId: ids.leadId,
        campaignId: ids.campaignId,
        purpose,
        model,
        inputTokens: 1200,
        outputTokens: 400,
        cacheReadTokens: 0,
        cacheWriteTokens: 0,
        durationMs: 5,
        stopReason: "end_turn",
        ok,
        error: ok ? null : "mock failure",
      });
    } catch {
      /* ignore in tests without DB */
    }
  }

  async research(input: ResearchInput): Promise<LlmResult<Persona>> {
    const ids = { leadId: input.lead.id, campaignId: input.lead.campaignId };
    if (this.flag(input, "fail-research")) {
      await this.record("research", input.model, ids, false);
      throw new Error("mock research failure");
    }
    const company = input.lead.company ?? input.lead.email.split("@")[1];
    const role = input.lead.jobTitle ?? "decision maker";
    const persona: Persona = {
      companySummary: `${company} is a ${input.lead.industry ?? "technology"} company${
        input.website?.description ? `: ${input.website.description}` : ""
      }.`,
      companyOffering: input.website?.headings.slice(0, 3) ?? ["core product"],
      industry: input.lead.industry ?? "unknown",
      companySizeSignal: "unknown (mock)",
      personRoleSummary: `${role} at ${company}, likely responsible for outcomes in their function.`,
      likelyPriorities: ["growth", "efficiency", "reliability"],
      painPoints: ["limited bandwidth", "manual processes", "scaling challenges"],
      recentSignals: [],
      personalisationHooks: [`${company} website`, `${role} role`],
      sources: input.website ? [input.website.url] : [],
      confidence: input.website ? "medium" : "low",
      notes: "Generated by mock provider.",
    };
    await this.record("research", input.model, ids, true);
    return {
      output: persona,
      model: input.model,
      usage: { inputTokens: 1200, outputTokens: 400, cacheReadTokens: 0, cacheWriteTokens: 0 },
      durationMs: 5,
      stopReason: "end_turn",
      notes: "mock findings",
    };
  }

  async draft(input: DraftInput): Promise<LlmResult<DraftOutput>> {
    const ids = { leadId: input.lead.id, campaignId: input.lead.campaignId };
    if (this.flag(input, "fail-draft")) {
      await this.record("draft", input.model, ids, false);
      throw new Error("mock draft failure");
    }
    const first = input.lead.firstName ?? "there";
    const company = input.lead.company ?? "your team";
    const service = input.services[0];
    const serviceName = service?.name ?? "our services";
    const isFollowUp = input.step.step > 1;
    let body: string;
    if (isFollowUp) {
      body = `Hi ${first},\n\nFollowing up on my note about ${serviceName}. ${input.persona.painPoints[0] ? `Teams like ${company} often mention ${input.persona.painPoints[0]}, and that is exactly where we help.` : ""}\n\nWould a short call next week be useful? Happy to share a relevant example beforehand.`;
    } else {
      body = `Hi ${first},\n\nI came across ${company} and noticed ${input.persona.personalisationHooks[0] ?? "your work"}. ${input.persona.painPoints[0] ? `Many ${input.persona.industry} teams tell us that ${input.persona.painPoints[0]} slows them down.` : ""}\n\nWe help with ${serviceName}${service?.valueProps[0] ? `: ${service.valueProps[0]}` : ""}. If useful, I can share a two-minute overview of how a similar team approached it.\n\nWould it make sense to compare notes for fifteen minutes next week?`;
    }
    if (this.flag(input, "long-draft") && !input.regenerationFeedback) {
      body += "\n\n" + "This sentence is padding to exceed the word limit. ".repeat(60);
    }
    if (this.flag(input, "banned") && !input.regenerationFeedback) {
      body += "\n\nThis is a limited time offer, act now.";
    }
    const out: DraftOutput = {
      selectedServices: service
        ? [{ serviceId: service.id, serviceName: service.name, fitScore: 7.5, rationale: "Best fit by description (mock)." }]
        : [],
      pitchAngle: `Connect ${company}'s ${input.persona.painPoints[0] ?? "priorities"} with ${serviceName}.`,
      subject: isFollowUp ? `Re: ${serviceName} for ${company}` : `${serviceName} for ${company}`,
      bodyText: body,
      callToAction: "15-minute call next week",
      personalisationUsed: input.persona.personalisationHooks.slice(0, 1),
      selfCheck: { wordCount: body.split(/\s+/).length, followsTone: true, followsRules: true, concerns: [] },
    };
    await this.record("draft", input.model, ids, true);
    return {
      output: out,
      model: input.model,
      usage: { inputTokens: 1500, outputTokens: 300, cacheReadTokens: 1000, cacheWriteTokens: 0 },
      durationMs: 5,
      stopReason: "end_turn",
    };
  }
}
