import type { DraftOutput, Persona } from "@mailapp/shared";
import type { DraftInput, LlmAdapter, LlmDeps, LlmResult, PreparedRequest, ResearchInput } from "./provider.js";
import { recordLlmCall } from "./usage.js";

const RESEARCH_USAGE = { inputTokens: 1200, outputTokens: 400, cacheReadTokens: 0, cacheWriteTokens: 0 };
const DRAFT_USAGE = { inputTokens: 1500, outputTokens: 300, cacheReadTokens: 1000, cacheWriteTokens: 0 };

/**
 * Deterministic provider for tests, CI and dry-runs. Produces plausible output from the lead
 * record alone; never calls the network. Behaviour can be tweaked per lead through the `notes`
 * column: "mock:fail-research", "mock:fail-draft", "mock:long-draft", "mock:banned".
 *
 * Mock rates are zero, so recorded calls carry tokens but no cost.
 */
export class MockLlmAdapter implements LlmAdapter {
  readonly provider = "mock" as const;
  constructor(private readonly deps: LlmDeps) {}

  private flag(input: { lead: { notes: string | null } }, f: string): boolean {
    return (input.lead.notes ?? "").includes(`mock:${f}`);
  }

  async research(input: ResearchInput): Promise<LlmResult<Persona>> {
    const ids = { leadId: input.lead.id, campaignId: input.lead.campaignId };
    if (this.flag(input, "fail-research")) {
      await recordLlmCall(this.deps, {
        purpose: "research",
        model: input.model,
        usage: RESEARCH_USAGE,
        durationMs: 5,
        stopReason: null,
        ok: false,
        error: "mock failure",
        ...ids,
      });
      throw new Error("mock research failure");
    }
    const persona = mockPersona(input);
    const cost = await recordLlmCall(this.deps, {
      purpose: "research",
      model: input.model,
      usage: RESEARCH_USAGE,
      durationMs: 5,
      stopReason: "end_turn",
      ok: true,
      error: null,
      ...ids,
    });
    return {
      output: persona,
      model: input.model.model,
      usage: RESEARCH_USAGE,
      durationMs: 5,
      stopReason: "end_turn",
      notes: "mock findings",
      costMicroUsd: cost,
    };
  }

  async draft(input: DraftInput): Promise<LlmResult<DraftOutput>> {
    const ids = { leadId: input.lead.id, campaignId: input.lead.campaignId };
    if (this.flag(input, "fail-draft")) {
      await recordLlmCall(this.deps, {
        purpose: "draft",
        model: input.model,
        usage: DRAFT_USAGE,
        durationMs: 5,
        stopReason: null,
        ok: false,
        error: "mock failure",
        ...ids,
      });
      throw new Error("mock draft failure");
    }
    const out = mockDraft(input, {
      long: this.flag(input, "long-draft") && !input.regenerationFeedback,
      banned: this.flag(input, "banned") && !input.regenerationFeedback,
    });
    const cost = await recordLlmCall(this.deps, {
      purpose: "draft",
      model: input.model,
      usage: DRAFT_USAGE,
      durationMs: 5,
      stopReason: "end_turn",
      ok: true,
      error: null,
      ...ids,
    });
    return { output: out, model: input.model.model, usage: DRAFT_USAGE, durationMs: 5, stopReason: "end_turn", costMicroUsd: cost };
  }

  /**
   * The mock provider has no batch endpoint, so a "batch" selection on it still produces a
   * request body; the batch runner executes mock items inline on the next tick, which keeps
   * the batch state machine testable without a network.
   */
  prepareResearch(input: ResearchInput): PreparedRequest {
    return { purpose: "research", model: input.model, body: { kind: "mock-research", leadId: input.lead.id } };
  }

  prepareDraft(input: DraftInput): PreparedRequest {
    return { purpose: "draft", model: input.model, body: { kind: "mock-draft", leadId: input.lead.id, step: input.step.step } };
  }
}

export function mockPersona(input: ResearchInput): Persona {
  const company = input.lead.company ?? input.lead.email.split("@")[1];
  const role = input.lead.jobTitle ?? "decision maker";
  return {
    companySummary: `${company} is a ${input.lead.industry ?? "technology"} company${
      input.website?.description ? `: ${input.website.description}` : ""
    }.`,
    companyOffering: input.website?.headings.slice(0, 3) ?? ["core product"],
    industry: input.lead.industry ?? "unknown",
    companySizeSignal: "unknown (mock)",
    personRoleSummary: `${role} at ${company}, likely responsible for outcomes in their function.`,
    likelyPriorities: ["growth", "efficiency", "reliability"],
    painPoints: ["limited bandwidth", "manual processes", "scaling challenges"],
    recentSignals: [],
    personalisationHooks: [`${company} website`, `${role} role`],
    sources: input.website ? [input.website.url] : [],
    confidence: input.website ? "medium" : "low",
    notes: "Generated by mock provider.",
  };
}

export function mockDraft(input: DraftInput, opts: { long?: boolean; banned?: boolean } = {}): DraftOutput {
  const first = input.lead.firstName ?? "there";
  const company = input.lead.company ?? "your team";
  const service = input.services[0];
  const serviceName = service?.name ?? "our services";
  const isFollowUp = input.step.step > 1;
  let body: string;
  if (isFollowUp) {
    body = `Hi ${first},\n\nFollowing up on my note about ${serviceName}. ${input.persona.painPoints[0] ? `Teams like ${company} often mention ${input.persona.painPoints[0]}, and that is exactly where we help.` : ""}\n\nWould a short call next week be useful? Happy to share a relevant example beforehand.`;
  } else {
    body = `Hi ${first},\n\nI came across ${company} and noticed ${input.persona.personalisationHooks[0] ?? "your work"}. ${input.persona.painPoints[0] ? `Many ${input.persona.industry} teams tell us that ${input.persona.painPoints[0]} slows them down.` : ""}\n\nWe help with ${serviceName}${service?.valueProps[0] ? `: ${service.valueProps[0]}` : ""}. If useful, I can share a two-minute overview of how a similar team approached it.\n\nWould it make sense to compare notes for fifteen minutes next week?`;
  }
  if (opts.long) body += "\n\n" + "This sentence is padding to exceed the word limit. ".repeat(60);
  if (opts.banned) body += "\n\nThis is a limited time offer, act now.";
  return {
    selectedServices: service
      ? [{ serviceId: service.id, serviceName: service.name, fitScore: 7.5, rationale: "Best fit by description (mock)." }]
      : [],
    pitchAngle: `Connect ${company}'s ${input.persona.painPoints[0] ?? "priorities"} with ${serviceName}.`,
    subject: isFollowUp ? `Re: ${serviceName} for ${company}` : `${serviceName} for ${company}`,
    bodyText: body,
    callToAction: "15-minute call next week",
    personalisationUsed: input.persona.personalisationHooks.slice(0, 1),
    selfCheck: { wordCount: body.split(/\s+/).length, followsTone: true, followsRules: true, concerns: [] },
  };
}
